### ISSUE TITLE
USERNAME - where can i find it?

### ISSUE THREAD

**Issue by HeisemerBub** [anzure/homebridge-netatmo-security#15]
Hello, how do I find the "USERNAME" after I logged in to my Netatmo account??? 
Is this the email address?

I would like to use netatmo in Homebridge also udn there for ask.

The password will certainly be the password with which I also log into my Netatmo account right?

here is the homebridge config with username udn pass:

{
            "platform": "netatmo",
            "name": "netatmo platform",
            "ttl": 5,
            "auth": {
    	        "client_id": "XXXXX Create at https://dev.netatmo.com/",
                "client_secret": "XXXXX Create at https://dev.netatmo.com/",
                "username": "your netatmo username",
                "password": "your netatmo password"
            }
        }

about an answer thanks a lot

**Comment by Anzure** [comment]
Hey! That is correct, the email adresse is the username.

**Comment by HeisemerBub** [comment]
Hi anzure, thanks for your anwer.

I have created an new app in developers and IDs were created. Then i put my email an my pass in the homebrige config but in the homebridge log i have an auth misstake.

What can i do?

best regards

**Comment by Anzure** [comment]
Make sure to choose sufficient scopes when generating the API token info.

**Comment by Anzure** [comment]
Check out this: https://dev.netatmo.com/apidocumentation/oauth

**Comment by HeisemerBub** [comment]
o.k. but so my config is o.k.  i posted or?

look, this is the log:
29.10.2022, 11:19:42] [Hue] homebridge-hue v0.13.46, node v16.18.0, homebridge v1.5.1
[29.10.2022, 11:19:42] [Hue] warning: planned changes, see https://github.com/ebaauw/homebridge-hue/issues/1070
[29.10.2022, 11:19:42] [Hue] warning: recommended version: node v16.17.1 LTS
[29.10.2022, 11:19:42] [Hue] warning: recommended version: homebridge v1.5.0
[29.10.2022, 11:19:42] [netatmo platform] Initializing netatmo platform...
[29.10.2022, 11:19:42] [Hue] Philips hue: Signify Netherlands B.V. BSB002 bridge v1953188020, api v1.53.0
[29.10.2022, 11:19:42] [Hue] Philips hue: warning: not using recommended Hue bridge api version 1.52.0
**[29.10.2022, 11:19:43] [netatmo platform] ERROR - Netatmo: Error: Authenticate error: invalid_client**

**Comment by HeisemerBub** [comment]
i have found the misstake.....
#
the " were not sitting in zhe right position.

Now the homebridge plugin is running :-)
